# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-17 06:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('family_center', '0002_auto_20170204_0746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_messenger_id', models.CharField(blank=True, max_length=256, null=True, unique=True)),
                ('chat_state', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='familyusermapping',
            name='user',
        ),
        migrations.AlterField(
            model_name='family',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family', to='family_center.Member'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='familyusermapping',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fu', to='family_center.Member'),
        ),
    ]
